/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MySQLJDBCExample;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

public class TestMysql {
	public static void main (String [] args ) throws ClassNotFoundException, SQLException{
        Class.forName("com.mysql.jdbc.Driver");
        String connectionUrl = "jdbc:mysql://localhost:3306/opentutorials?useUnicode=true&characterEncoding=UTF-8&user=root&password=koreait";
        Connection conn = DriverManager.getConnection(connectionUrl);
        ResultSet rs = conn.prepareStatement("show tables").executeQuery();
 
        while(rs.next()){
            String s = rs.getString(1);
            System.out.println(s);
        }

        PreparedStatement ps = conn.prepareStatement("INSERT INTO topic VALUES(NULL, 'Java', 'Java is ...', NOW());");
        if (!ps.execute()) {
            System.out.println(ps.getUpdateCount());
        }
    }
}
